#!/bin/sh
. "$(dirname "$0")/_/husky.sh"

# Initial message
echo '  \e[1;43m VERIFYING CHANGES PREVIOUSLY ADDED \e[1;0m
'

# Running message
echo '
  \e[1;44m RUNNING: type verification \e[1;0m

  \e[1m\e[1;34mRunning\e[1;37m type verification...
  '

## Running check-types
npm run check-types ||
(
  echo '\e[1;41m FAILED: type verification \e[1;0m
  '
  false;
)

# Success message
echo '
  \e[1;42m SUCCEED: type verificaton \e[1;0m

  \e[1mType verification \e[1;32msucceed\e[1;37m.
  '

# Running message
echo '
  \e[1;44m RUNNING: format verification \e[1;0m

  \e[1m\e[1;34mRunning\e[1;37m format verification...
  '

## Running check-format
npm run check-format ||
(
  echo '
  \e[1;41m FAILED: format verification \e[1;0m

  \e[1m\e[4mTo fix, follow the following steps:\e[1;0m

    \e[1;34m1.\e[1;0m Run \e[1;34m`npm run format`\e[1;0m

    \e[1;34m2.\e[1;0m \e[1mAdd changes\e[1;0m

    \e[1;34m3.\e[1;0m \e[1mTry to commit again\e[1;0m
    '
  false;
)

# Success message
echo '
  \e[1;42m SUCCEED: format verificaton \e[1;0m

  \e[1mFormat verification \e[1;32msucceed\e[1;37m.
  '

# Running message
echo '
  \e[1;44m RUNNING: eslint verification \e[1;0m

  \e[1m\e[1;34mRunning\e[1;37m eslint verification...
  '

## Running check-lint
npm run check-lint ||
(
  echo '
  \e[1;41m FAILED: eslint verification \e[1;0m

  \e[1m\e[4mTo fix, follow the following steps:\e[1;0m

    \e[1;34m1.\e[1;0m \e[1mMake the required changes listed above\e[1;0m

    \e[1;34m2.\e[1;0m \e[1mAdd changes\e[1;0m

    \e[1;34m3.\e[1;0m \e[1mTry to commit again\e[1;0m
    '
  false;
)

# Success message
echo '
  \e[1;42m SUCCEED: eslint verificaton \e[1;0m

  \e[1mEslint verification \e[1;32msucceed\e[1;37m.
  '

# Success message
echo '
  \e[1;42m SUCCEED: everything right \e[1;0m

  \e[1mSucceed running \e[1;34m`check-types`\e[1;0m\e[1m,\e[1;0m \e[1;34m`check-format`\e[1;0m \e[1mand\e[1;0m \e[1;34m`check-lint`\e[1;0m.\e[1;0m

  \e[1mTrying to \e[1;34m`run build`\e[1;0m\e[1m.\e[1;0m
  '

# Running message
echo '
  \e[1;44m RUNNING: build \e[1;0m

  \e[1m\e[1;34mRunning\e[1;37m build...
  '

## Running build
npm run build ||
(
  echo '
  \e[1;41m FAILED: run build \e[1;0m

  \e[1mNext run build \e[1;31mfailed\e[1;0m\e[1m. Consult the errors above.\e[1;0m
  '
  false;
)

# Success message
echo '
  \e[1;42m SUCCEED: run build \e[1;0m

  \e[1mNext run build \e[1;32msucceed\e[1;37m.

  Previously added changes \e[1;32msucceed\e[1;37m passing through the system verifications.

  Changes are beeing \e[4m\e[1;34mcommitted\e[1;0m\e[1m.
  '
